interface McpToolDefinition {
  name: string;
  description: string;
  inputSchema: {
    type: 'object';
    properties: Record<string, unknown>;
    required?: string[];
  };
}

interface McpToolExport {
  tools: McpToolDefinition[];
  callTool: (name: string, args: Record<string, unknown>) => Promise<unknown>;
  meter?: { credits: number };
  cost?: Record<string, unknown>;
  provider?: string;
}

/**
 * US News Feeds MCP.
 *
 * US news, politics, policy, defense & government — national, regional and agency sources.
 * CF-robust RSS / Atom / RDF reader over a curated, edge-verified registry; on a
 * Cloudflare egress block it falls back to the rss2json proxy. (Generated by
 * scripts/gen-feeds-packs.mjs from scripts/feeds-registry.mjs — do not hand-edit.)
 */


const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';
const PROXY = 'https://api.rss2json.com/v1/api.json';
const MAX_ITEMS = 50;

interface FeedDef { title: string; url: string; category: string; source: string; description: string }

const FEEDS: Record<string, FeedDef> = {
  'npr-news': { title: "NPR News", url: "https://feeds.npr.org/1001/rss.xml", category: "news", source: "npr.org", description: "NPR top news" },
  'fda-press': { title: "FDA Press Releases", url: "https://www.fda.gov/about-fda/contact-fda/stay-informed/rss-feeds/press-releases/rss.xml", category: "government", source: "fda.gov", description: "US FDA press releases (drugs, food, devices)" },
  'ftc-consumer': { title: "FTC Consumer Protection", url: "https://www.ftc.gov/feeds/press-release-consumer-protection.xml", category: "government", source: "ftc.gov", description: "US FTC consumer-protection press releases (scams, fraud, refunds)" },
  'nyt-world': { title: "New York Times — World", url: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml", category: "news", source: "nytimes.com", description: "NYT world news" },
  propublica: { title: "ProPublica", url: "https://www.propublica.org/feeds/propublica/main", category: "news", source: "propublica.org", description: "Investigative journalism" },
  cnn: { title: "CNN", url: "http://rss.cnn.com/rss/edition.rss", category: "news", source: "cnn.com", description: "CNN international news" },
  politico: { title: "Politico", url: "https://www.politico.com/rss/politicopicks.xml", category: "news", source: "politico.com", description: "US politics & policy" },
  axios: { title: "Axios", url: "https://api.axios.com/feed/", category: "news", source: "axios.com", description: "Concise news across politics, business & tech" },
  'cbs-news': { title: "CBS News", url: "https://www.cbsnews.com/latest/rss/main", category: "news", source: "cbsnews.com", description: "CBS News (US) top stories" },
  'foreign-policy': { title: "Foreign Policy", url: "https://foreignpolicy.com/feed/", category: "news", source: "foreignpolicy.com", description: "International affairs & geopolitics" },
  'nbc-news': { title: "NBC News", url: "https://feeds.nbcnews.com/nbcnews/public/news", category: "news", source: "nbcnews.com", description: "NBC News (US) top stories" },
  vox: { title: "Vox", url: "https://www.vox.com/rss/index.xml", category: "news", source: "vox.com", description: "Explanatory news & analysis" },
  'the-intercept': { title: "The Intercept", url: "https://theintercept.com/feed/", category: "news", source: "theintercept.com", description: "Investigative journalism" },
  'the-atlantic': { title: "The Atlantic", url: "https://www.theatlantic.com/feed/all/", category: "news", source: "theatlantic.com", description: "Politics, culture & ideas (long-form)" },
  calmatters: { title: "CalMatters", url: "https://calmatters.org/feed/", category: "news", source: "calmatters.org", description: "California politics & policy" },
  'the-markup': { title: "The Markup", url: "https://themarkup.org/feeds/rss.xml", category: "news", source: "themarkup.org", description: "Tech-accountability investigative journalism" },
  'the-19th': { title: "The 19th", url: "https://19thnews.org/feed/", category: "news", source: "19thnews.org", description: "Gender, politics & policy" },
  'texas-tribune': { title: "The Texas Tribune", url: "https://www.texastribune.org/feeds/main/", category: "news", source: "texastribune.org", description: "Texas politics & policy" },
  'smart-cities-dive': { title: "Smart Cities Dive", url: "https://www.smartcitiesdive.com/feeds/news/", category: "government", source: "smartcitiesdive.com", description: "Smart cities & urban-tech news" },
  'the-hill': { title: "The Hill", url: "https://thehill.com/news/feed/", category: "government", source: "thehill.com", description: "US politics & policy" },
  govexec: { title: "Government Executive", url: "https://www.govexec.com/rss/all/", category: "government", source: "govexec.com", description: "US federal-government management news" },
  'defense-one': { title: "Defense One", url: "https://www.defenseone.com/rss/all/", category: "government", source: "defenseone.com", description: "US defense & national-security news" },
  'war-on-the-rocks': { title: "War on the Rocks", url: "https://warontherocks.com/feed/", category: "government", source: "warontherocks.com", description: "National security & military strategy" },
  'foreign-affairs': { title: "Foreign Affairs", url: "https://www.foreignaffairs.com/rss.xml", category: "news", source: "foreignaffairs.com", description: "International relations & foreign policy" },
};

const tools: McpToolExport['tools'] = [
  {
    name: 'list_feeds',
    description: 'List the curated US news, politics & government feeds (id, title, category, source). Optionally filter by category (government, news) or keyword. Pass an id to read_feed.',
    inputSchema: {
      type: 'object',
      properties: {
        category: { type: 'string', description: 'Filter by category: government, news.' },
        query: { type: 'string', description: 'Keyword to match in feed title/source/description.' },
      },
    },
  },
  {
    name: 'read_feed',
    description: 'Read a curated US news, politics & government feed by its id (from list_feeds). Returns normalized items (title, link, published, summary). Optionally filter items by keyword.',
    inputSchema: {
      type: 'object',
      properties: {
        feed: { type: 'string', description: 'Curated feed id (from list_feeds).' },
        query: { type: 'string', description: 'Keyword filter over item title/summary.' },
        limit: { type: 'number', description: 'Max items (1-50, default 20).' },
      },
      required: ['feed'],
    },
  },
  {
    name: 'fetch_feed',
    description: 'Fetch and normalize any RSS / Atom / RDF feed by URL. CF-robust: fetches directly and falls back to a proxy if the source blocks the gateway. Use list_feeds first for curated sources.',
    inputSchema: {
      type: 'object',
      properties: {
        url: { type: 'string', description: 'Feed URL, e.g. "https://news.ycombinator.com/rss".' },
        query: { type: 'string', description: 'Keyword filter over item title/summary.' },
        limit: { type: 'number', description: 'Max items (1-50, default 20).' },
      },
      required: ['url'],
    },
  },
];

async function callTool(name: string, args: Record<string, unknown>): Promise<unknown> {
  switch (name) {
    case 'list_feeds':
      return listFeeds(args);
    case 'read_feed': {
      const id = String(args.feed ?? '').trim();
      const def = FEEDS[id];
      if (!def) throw new Error(`Unknown feed "${args.feed}". Use list_feeds to see valid ids.`);
      return readFeed(def.url, args, { id, ...def });
    }
    case 'fetch_feed': {
      const url = String(args.url ?? '').trim();
      if (!/^https?:\/\//i.test(url)) throw new Error('Pass a valid feed `url` (http/https).');
      return readFeed(url, args);
    }
    default:
      throw new Error(`Unknown tool: ${name}`);
  }
}

function listFeeds(args: Record<string, unknown>): unknown {
  const cat = typeof args.category === 'string' ? args.category.trim().toLowerCase() : '';
  const q = typeof args.query === 'string' ? args.query.trim().toLowerCase() : '';
  const feeds = Object.entries(FEEDS)
    .filter(([, d]) => (!cat || d.category === cat) && (!q || `${d.title} ${d.source} ${d.description}`.toLowerCase().includes(q)))
    .map(([id, d]) => ({ id, title: d.title, category: d.category, source: d.source, description: d.description }));
  return { categories: [...new Set(Object.values(FEEDS).map((d) => d.category))].sort(), count: feeds.length, feeds };
}

async function readFeed(url: string, args: Record<string, unknown>, meta?: Record<string, unknown>): Promise<unknown> {
  const limit = clamp(numArg(args.limit, 20), 1, MAX_ITEMS);
  const q = typeof args.query === 'string' ? args.query.trim().toLowerCase() : '';
  const { items, via } = await getFeed(url);
  let out = items;
  if (q) out = out.filter((i) => `${i.title} ${i.summary}`.toLowerCase().includes(q));
  return {
    feed: meta ? { id: meta.id, title: meta.title, source: meta.source } : { url },
    via,
    total_matching: out.length,
    count: Math.min(out.length, limit),
    items: out.slice(0, limit),
  };
}

interface FeedItem { title: string; link: string; published?: string; summary?: string; author?: string; categories?: string[]; id?: string }

async function getFeed(url: string): Promise<{ items: FeedItem[]; via: string }> {
  try {
    const res = await fetch(url, { headers: { 'User-Agent': UA, Accept: 'application/rss+xml, application/atom+xml, application/xml, text/xml, */*' } });
    if (res.ok) {
      const xml = await res.text();
      if (/<(item|entry)[\s>]/i.test(xml)) return { items: parseFeed(xml), via: 'direct' };
    }
  } catch {
    /* fall through to proxy */
  }
  const pres = await fetch(`${PROXY}?rss_url=${encodeURIComponent(url)}&count=${MAX_ITEMS}`, { headers: { 'User-Agent': UA, Accept: 'application/json' } });
  const body = (await pres.json().catch(() => ({}))) as { status?: string; items?: ProxyItem[] };
  if (body.status === 'ok' && Array.isArray(body.items)) {
    return {
      items: body.items.map((i) => ({
        title: clean(i.title), link: i.link || '', published: i.pubDate || undefined,
        summary: clean(i.description)?.slice(0, 500) || undefined, author: i.author || undefined,
        categories: Array.isArray(i.categories) ? i.categories : undefined, id: i.guid || i.link,
      })),
      via: 'proxy',
    };
  }
  throw new Error(`Feed unreachable: ${url} (blocked directly and via proxy). The source may block datacenter egress.`);
}

interface ProxyItem { title?: string; link?: string; pubDate?: string; description?: string; author?: string; categories?: string[]; guid?: string }

function parseFeed(xml: string): FeedItem[] {
  const out: FeedItem[] = [];
  const blocks = xml.match(/<(item|entry)[\s>][\s\S]*?<\/\1>/gi) ?? [];
  for (const b of blocks) {
    const link = extractLink(b);
    out.push({
      title: clean(tag(b, 'title')),
      link,
      published: tag(b, 'pubDate') || tag(b, 'published') || tag(b, 'updated') || tag(b, 'dc:date') || undefined,
      summary: clean(tag(b, 'description') || tag(b, 'summary') || tag(b, 'content:encoded') || tag(b, 'content'))?.slice(0, 500) || undefined,
      author: clean(tag(b, 'dc:creator') || authorName(b)) || undefined,
      categories: cats(b),
      id: tag(b, 'guid') || tag(b, 'id') || link,
    });
  }
  return out;
}

function extractLink(b: string): string {
  const rss = b.match(/<link>([\s\S]*?)<\/link>/i);
  if (rss && rss[1].trim()) return clean(rss[1]);
  const alt = b.match(/<link[^>]*rel=["']alternate["'][^>]*href=["']([^"']+)["']/i) || b.match(/<link[^>]*href=["']([^"']+)["']/i);
  return alt ? alt[1].trim() : '';
}
function authorName(b: string): string {
  const a = b.match(/<author>([\s\S]*?)<\/author>/i);
  if (!a) return '';
  const name = a[1].match(/<name>([\s\S]*?)<\/name>/i);
  return name ? name[1] : a[1];
}
function cats(b: string): string[] | undefined {
  const list: string[] = [];
  for (const m of b.matchAll(/<category[^>]*?(?:term=["']([^"']+)["'][^>]*)?>([\s\S]*?)<\/category>/gi)) {
    const v = clean(m[1] || m[2]);
    if (v) list.push(v);
  }
  for (const m of b.matchAll(/<category[^>]*term=["']([^"']+)["'][^>]*\/>/gi)) list.push(m[1]);
  return list.length ? [...new Set(list)].slice(0, 10) : undefined;
}
function tag(xml: string, name: string): string {
  const m = xml.match(new RegExp(`<${name.replace(':', '\\:')}[^>]*>([\\s\\S]*?)<\\/${name.replace(':', '\\:')}>`, 'i'));
  return m ? unwrap(m[1]) : '';
}
function unwrap(s: string): string {
  const m = s.trim().match(/^<!\[CDATA\[([\s\S]*?)\]\]>$/);
  return (m ? m[1] : s).trim();
}
function clean(s: unknown): string {
  if (typeof s !== 'string') return '';
  return s
    .replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, '$1')
    .replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/<\/?[a-zA-Z][^>]*>/g, ' ')
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(Number(d)))
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&quot;/g, '"').replace(/&#39;|&apos;/g, "'").replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&')
    .replace(/\s+/g, ' ').trim();
}
function numArg(v: unknown, dflt: number): number {
  const n = typeof v === 'number' ? v : typeof v === 'string' ? Number(v) : NaN;
  return Number.isFinite(n) ? n : dflt;
}
function clamp(n: number, lo: number, hi: number): number {
  return Math.max(lo, Math.min(hi, Math.trunc(n)));
}

export default { tools, callTool, meter: { credits: 1 } } satisfies McpToolExport;
